language: java
jdk:
  - openjdk11
stages:
  - tests-sonar
  - deploy
  
jobs:
  include:
  - stage: tests-sonar
    addons:
      sonarcloud:
        organization: "savitoh"
        secure: $KEY_SONAR
    before_script: cd demo-qr-code-api
    script:
      - mvn clean install sonar:sonar
  - stage: deploy
    script: echo "Deploying... (noop)"

